//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <assert.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t _fini(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int32_t * _Z10A_PrintStmP10A_expList_(int64_t * a1);
int32_t * _Z11A_AssignStmPKcP6A_exp_(char * a1, int64_t * a2);
int32_t * _Z13A_CompoundStmP6A_stm_S0_(int64_t * a1, int64_t * a2);
int32_t * _Z13A_LastExpListP6A_exp_(int64_t * a1);
int32_t * _Z13A_PairExpListP6A_exp_P10A_expList_(int64_t * a1, int64_t * a2);
int32_t * _Z13interpExpListP10A_expList_P5table(int64_t * a1, int64_t * a2);
char * _Z14checked_mallocm(int64_t size);
int32_t * _Z14prog_generatorv(void);
int32_t * _Z15prog_generator2v(void);
int32_t _Z3maxIiET_S0_S0_(int32_t a1, int32_t a2);
int32_t * _Z5TablePKciP5table(char * a1, int32_t a2, int64_t * a3);
void _Z6interpP6A_stm_(int64_t * a1);
int32_t _Z6lookupP5tablePKc(int64_t * a1, char * str2);
char * _Z6StringPKc(char * str);
int32_t * _Z6updateP5tablePKci(int64_t * a1, char * a2, int32_t a3);
int32_t * _Z7A_IdExpPKc(char * a1);
int32_t * _Z7A_OpExpP6A_exp_7A_binopS0_(int64_t * a1, int64_t a2, int64_t * a3);
int32_t _Z7maxargsP6A_stm_(int64_t * a1);
int32_t * _Z8A_NumExpi(int32_t a1);
void _Z8update_eP6A_exp_RiS1_RbS2_(int64_t * a1, int32_t * a2, int32_t * a3, bool * a4, bool * a5);
void _Z8update_sP6A_stm_RiS1_RbS2_(int64_t * a1, int32_t * a2, int32_t * a3, bool * a4, bool * a5);
int32_t * _Z9A_EseqExpP6A_stm_P6A_exp_(int64_t * a1, int64_t * a2);
int32_t * _Z9interpExpP6A_exp_P5table(int64_t * a1, int64_t * a2);
int32_t * _Z9interpStmP6A_stm_P5table(int64_t * a1, int64_t * a2);
void _Z9update_elP10A_expList_RiS1_RbS2_(int64_t * a1, int32_t * a2, int32_t * a3, bool * a4, bool * a5);
int64_t deregister_tm_clones(void);
int64_t frame_dummy(void);
void function_10c0(int64_t * d);
int32_t function_10d0(char * s);
void function_10e0(char * assertion, char * file, int32_t line, char * function);
char * function_10f0(char * dest, char * src);
int64_t function_1100(int64_t * a1, char * a2);
int64_t function_1110(int64_t * (*a1)(int64_t *));
void function_1120(void);
int64_t * function_1130(int32_t size);
int32_t function_1140(char * s1, char * s2);
int64_t function_1150(int32_t a1);
int64_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

int64_t g1 = 0; // 0x4fd0
int64_t * (*g2)(int64_t *) = NULL; // 0x5040
char g3 = 0; // 0x5150
int32_t g4;

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());
void __stack_chk_fail(void);
int64_t _ZNSolsEi(int32_t a1);
int64_t _ZNSolsEPFRSoS_E(int64_t * (*a1)(int64_t *));
int64_t _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(int64_t * a1, char * a2);

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x101b
int64_t _init(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x4ff0 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g4;
    }
    // 0x1016
    return result;
}

// Address range: 0x10c0 - 0x10ca
void function_10c0(int64_t * d) {
    // 0x10c0
    __cxa_finalize(d);
}

// Address range: 0x10d0 - 0x10da
int32_t function_10d0(char * s) {
    // 0x10d0
    return strlen(s);
}

// Address range: 0x10e0 - 0x10ea
void function_10e0(char * assertion, char * file, int32_t line, char * function) {
    // 0x10e0
    __assert_fail(assertion, file, line, function);
}

// Address range: 0x10f0 - 0x10fa
char * function_10f0(char * dest, char * src) {
    // 0x10f0
    return strcpy(dest, src);
}

// Address range: 0x1100 - 0x110a
int64_t function_1100(int64_t * a1, char * a2) {
    // 0x1100
    return _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc(a1, a2);
}

// Address range: 0x1110 - 0x111a
int64_t function_1110(int64_t * (*a1)(int64_t *)) {
    // 0x1110
    return _ZNSolsEPFRSoS_E(a1);
}

// Address range: 0x1120 - 0x112a
void function_1120(void) {
    // 0x1120
    __stack_chk_fail();
}

// Address range: 0x1130 - 0x113a
int64_t * function_1130(int32_t size) {
    // 0x1130
    return malloc(size);
}

// Address range: 0x1140 - 0x114a
int32_t function_1140(char * s1, char * s2) {
    // 0x1140
    return strcmp(s1, s2);
}

// Address range: 0x1150 - 0x115a
int64_t function_1150(int32_t a1) {
    // 0x1150
    return _ZNSolsEi(a1);
}

// Address range: 0x1160 - 0x1186
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x1160
    int64_t v1; // 0x1160
    __libc_start_main(0x1ee1, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x1190 - 0x11b9
int64_t deregister_tm_clones(void) {
    // 0x1190
    return 0x5010;
}

// Address range: 0x11c0 - 0x11f9
int64_t register_tm_clones(void) {
    // 0x11c0
    return 0;
}

// Address range: 0x1200 - 0x1239
int64_t __do_global_dtors_aux(void) {
    // 0x1200
    if (g3 != 0) {
        // 0x1238
        int64_t result; // 0x1200
        return result;
    }
    // 0x120d
    if (g1 != 0) {
        // 0x121b
        __cxa_finalize((int64_t *)*(int64_t *)0x5008);
    }
    int64_t result2 = deregister_tm_clones(); // 0x1227
    g3 = 1;
    return result2;
}

// Address range: 0x1240 - 0x1249
int64_t frame_dummy(void) {
    // 0x1240
    return register_tm_clones();
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/main.cpp
// Address range: 0x1249 - 0x1295
// Line range:    33 - 37
// Demangled:     Table(char const*, int, table*)
int32_t * _Z5TablePKciP5table(char * a1, int32_t a2, int64_t * a3) {
    char * v1 = _Z14checked_mallocm(24); // 0x1265
    int64_t v2 = (int64_t)v1; // 0x1265
    *(int64_t *)v1 = (int64_t)a1;
    *(int32_t *)(v2 + 8) = a2;
    *(int64_t *)(v2 + 16) = (int64_t)a3;
    return (int32_t *)v1;
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/main.hpp
// Address range: 0x1295 - 0x1388
// Line range:    22 - 37
// Demangled:     update_e(A_exp_*, int&, int&, bool&, bool&)
void _Z8update_eP6A_exp_RiS1_RbS2_(int64_t * a1, int32_t * a2, int32_t * a3, bool * a4, bool * a5) {
    int64_t v1 = (int64_t)a1;
    int64_t v2; // 0x1295
    int32_t v3 = v2;
    if (v3 == 2) {
        // 0x12c0
        *(char *)a5 = 0;
        _Z8update_eP6A_exp_RiS1_RbS2_((int64_t *)*(int64_t *)(v1 + 8), a2, a3, a4, a5);
        _Z8update_eP6A_exp_RiS1_RbS2_((int64_t *)*(int64_t *)(v1 + 24), a2, a3, a4, a5);
    }
    if (v3 == 3) {
        // 0x1328
        *(char *)a5 = 0;
        _Z8update_sP6A_stm_RiS1_RbS2_((int64_t *)*(int64_t *)(v1 + 8), a2, a3, a4, a5);
        _Z8update_eP6A_exp_RiS1_RbS2_((int64_t *)*(int64_t *)(v1 + 16), a2, a3, a4, a5);
    }
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/main.hpp
// Address range: 0x1388 - 0x14b6
// Line range:    40 - 58
// Demangled:     update_el(A_expList_*, int&, int&, bool&, bool&)
void _Z9update_elP10A_expList_RiS1_RbS2_(int64_t * a1, int32_t * a2, int32_t * a3, bool * a4, bool * a5) {
    int64_t v1 = (int64_t)a1;
    int64_t v2; // 0x1388
    int32_t v3 = v2;
    char v4 = v2;
    int32_t v5 = v2;
    int32_t v6 = v2;
    if (v3 == 0) {
        if (v4 != 0) {
            // 0x13c1
            *a2 = v5 + 1;
        }
        int64_t v7 = *(int64_t *)(v1 + 16); // 0x13e0
        _Z8update_eP6A_exp_RiS1_RbS2_((int64_t *)*(int64_t *)(v1 + 8), a2, a3, a4, a5);
        _Z9update_elP10A_expList_RiS1_RbS2_((int64_t *)v7, a2, a3, a4, a5);
        *a3 = _Z3maxIiET_S0_S0_(v6, v5);
    }
    if (v3 != 1) {
        // 0x14b3
        return;
    }
    if (v4 != 0) {
        // 0x1457
        *a2 = v5 + 1;
    }
    // 0x1466
    _Z8update_eP6A_exp_RiS1_RbS2_((int64_t *)*(int64_t *)(v1 + 8), a2, a3, a4, a5);
    *a3 = _Z3maxIiET_S0_S0_(v6, v5);
    *(char *)a4 = 0;
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/main.hpp
// Address range: 0x14b6 - 0x15cc
// Line range:    61 - 80
// Demangled:     update_s(A_stm_*, int&, int&, bool&, bool&)
void _Z8update_sP6A_stm_RiS1_RbS2_(int64_t * a1, int32_t * a2, int32_t * a3, bool * a4, bool * a5) {
    int64_t v1 = (int64_t)a1;
    int64_t v2; // 0x14b6
    int32_t v3 = v2;
    if (v3 == 0) {
        // 0x14e5
        _Z8update_sP6A_stm_RiS1_RbS2_((int64_t *)*(int64_t *)(v1 + 8), a2, a3, a4, a5);
        _Z8update_sP6A_stm_RiS1_RbS2_((int64_t *)*(int64_t *)(v1 + 16), a2, a3, a4, a5);
    }
    if (v3 == 1) {
        // 0x1541
        _Z8update_eP6A_exp_RiS1_RbS2_((int64_t *)*(int64_t *)(v1 + 16), a2, a3, a4, a5);
    }
    if (v3 == 2) {
        // 0x1572
        *(char *)a4 = 1;
        *a2 = 0;
        _Z9update_elP10A_expList_RiS1_RbS2_((int64_t *)*(int64_t *)(v1 + 8), a2, a3, a4, a5);
        *a3 = _Z3maxIiET_S0_S0_((int32_t)v2, (int32_t)v2);
    }
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/main.hpp
// Address range: 0x15cc - 0x1639
// Line range:    83 - 90
// Demangled:     maxargs(A_stm_*)
int32_t _Z7maxargsP6A_stm_(int64_t * a1) {
    int64_t v1 = __readfsqword(40); // 0x15dc
    char v2 = 0; // bp-26, 0x15eb
    int32_t v3 = 0; // bp-24, 0x15ef
    int32_t v4 = 0; // bp-20, 0x15f6
    char v5 = 0; // bp-25, 0x15fd
    _Z8update_sP6A_stm_RiS1_RbS2_(a1, &v3, &v4, (bool *)&v2, (bool *)&v5);
    int32_t result = v4; // 0x1630
    if (v1 != __readfsqword(40)) {
        // 0x1632
        __stack_chk_fail();
        result = &g4;
    }
    // 0x1637
    return result;
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/main.hpp
// Address range: 0x1639 - 0x1685
// Line range:    97 - 101
// Demangled:     update(table*, char const*, int)
int32_t * _Z6updateP5tablePKci(int64_t * a1, char * a2, int32_t a3) {
    char * v1 = _Z14checked_mallocm(24); // 0x1655
    int64_t v2 = (int64_t)v1; // 0x1655
    *(int64_t *)v1 = (int64_t)a2;
    *(int32_t *)(v2 + 8) = a3;
    *(int64_t *)(v2 + 16) = (int64_t)a1;
    return (int32_t *)v1;
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/main.hpp
// Address range: 0x1685 - 0x16e0
// Line range:    106 - 114
// Demangled:     lookup(table*, char const*)
int32_t _Z6lookupP5tablePKc(int64_t * a1, char * str2) {
    // 0x1685
    if (a1 == NULL) {
        // 0x16de
        return -1;
    }
    int64_t str = (int64_t)a1;
    while (strcmp((char *)*(int64_t *)str, str2) != 0) {
        int64_t v1 = *(int64_t *)(str + 16); // 0x16ca
        if (v1 == 0) {
            // 0x16de
            return -1;
        }
        str = v1;
    }
    // 0x16de
    return *(int32_t *)(str + 8);
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/main.hpp
// Address range: 0x16e0 - 0x189b
// Line range:    119 - 153
// Demangled:     interpStm(A_stm_*, table*)
int32_t * _Z9interpStmP6A_stm_P5table(int64_t * a1, int64_t * a2) {
    // 0x16e0
    if (a1 == NULL) {
        // 0x1899
        return (int32_t *)0;
    }
    int64_t v1 = (int64_t)a1;
    int64_t v2; // 0x16e0
    int32_t v3 = v2;
    _Z14checked_mallocm(24);
    _Z14checked_mallocm(16);
    if (v3 != 2) {
        // 0x1730
        if (v3 > 2) {
            // 0x1899
            return (int32_t *)0;
        }
        int64_t v4 = 0; // 0x16e0
        switch (v3) {
            case 0: {
                int32_t * v5 = _Z9interpStmP6A_stm_P5table((int64_t *)*(int64_t *)(v1 + 8), a2); // 0x1759
                int64_t v6 = *(int64_t *)(v1 + 16); // 0x1766
                v4 = (int64_t)_Z9interpStmP6A_stm_P5table((int64_t *)v6, (int64_t *)v5);
                // break -> 0x1899
                break;
            }
            case 1: {
                int32_t * v7 = _Z9interpExpP6A_exp_P5table((int64_t *)*(int64_t *)(v1 + 16), a2); // 0x1798
                int32_t v8 = *v7; // 0x17a5
                int64_t v9 = *(int64_t *)(v1 + 8); // 0x17ab
                int64_t v10 = *(int64_t *)((int64_t)v7 + 8); // 0x17b3
                v4 = (int64_t)_Z6updateP5tablePKci((int64_t *)v10, (char *)v9, v8);
                // break -> 0x1899
                break;
            }
        }
        // 0x1899
        return (int32_t *)v4;
    }
    int64_t v11 = *(int64_t *)(v1 + 8);
    int64_t v12 = *(int64_t *)(v11 + 8);
    int32_t * v13 = _Z9interpExpP6A_exp_P5table((int64_t *)v12, a2); // 0x17e4
    if (*(int32_t *)v11 != 1) {
        int64_t v14 = _ZNSolsEi((int32_t)&g2); // 0x1869
        _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc((int64_t *)v14, " ");
        int64_t v15 = *(int64_t *)(v11 + 16);
        v13 = _Z9interpExpP6A_exp_P5table((int64_t *)*(int64_t *)(v15 + 8), a2);
        int64_t v16 = v15; // 0x17e4
        while (*(int32_t *)v15 != 1) {
            // 0x183c
            v14 = _ZNSolsEi((int32_t)&g2);
            _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc((int64_t *)v14, " ");
            v15 = *(int64_t *)(v16 + 16);
            v13 = _Z9interpExpP6A_exp_P5table((int64_t *)*(int64_t *)(v15 + 8), a2);
            v16 = v15;
        }
    }
    // 0x17e6
    _ZNSolsEi((int32_t)&g2);
    _ZNSolsEPFRSoS_E((int64_t * (*)(int64_t *))&g2);
    // 0x1899
    return (int32_t *)*(int64_t *)((int64_t)v13 + 8);
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/main.hpp
// Address range: 0x189b - 0x1a48
// Line range:    158 - 205
// Demangled:     interpExp(A_exp_*, table*)
int32_t * _Z9interpExpP6A_exp_P5table(int64_t * a1, int64_t * a2) {
    // 0x189b
    if (a1 == NULL) {
        // 0x1a46
        return (int32_t *)0;
    }
    // 0x18c0
    int64_t v1; // 0x189b
    int32_t v2 = v1;
    char * v3 = _Z14checked_mallocm(16); // 0x18c5
    if (v2 == 3) {
        int64_t v4 = (int64_t)a1; // 0x1a05
        int32_t * v5 = _Z9interpStmP6A_stm_P5table((int64_t *)*(int64_t *)(v4 + 8), a2); // 0x1a17
        int64_t v6 = *(int64_t *)(v4 + 16); // 0x1a24
        int64_t v7 = (int64_t)_Z9interpExpP6A_exp_P5table((int64_t *)v6, (int64_t *)v5);
        return (int32_t *)v7;
    }
    // 0x18dd
    if (v2 > 3) {
        // 0x1a46
        return (int32_t *)0;
    }
    int64_t v8 = (int64_t)a2;
    switch (v2) {
        case 2: {
            int64_t v9 = (int64_t)a1; // 0x1956
            int32_t * v10 = _Z9interpExpP6A_exp_P5table((int64_t *)*(int64_t *)(v9 + 8), a2); // 0x1968
            int32_t v11 = *v10; // 0x1975
            int64_t v12 = *(int64_t *)((int64_t)v10 + 8); // 0x197e
            int64_t v13 = *(int64_t *)(v9 + 24); // 0x1986
            int32_t * v14 = _Z9interpExpP6A_exp_P5table((int64_t *)v13, (int64_t *)v12); // 0x1990
            uint32_t v15 = *(int32_t *)(v9 + 16); // 0x199d
            int32_t v16; // 0x189b
            if (v15 == 3) {
                uint32_t v17 = *v14; // 0x19ea
                v16 = (0x100000000 * (int64_t)(v11 >> 31) | (int64_t)v11) / (int64_t)v17;
                // 0x19f6
                *v14 = v16;
                // 0x1a46
                return (int32_t *)(int64_t)v14;
            }
            // 0x19a5
            v16 = v11;
            if (v15 <= 3) {
                // 0x19aa
                v16 = v11;
                switch (v15) {
                    case 2: {
                        // 0x19d5
                        v16 = *v14 * v11;
                        // break -> 0x19f6
                        break;
                    }
                    case 0: {
                        // 0x19bf
                        v16 = *v14 + v11;
                        // break -> 0x19f6
                        break;
                    }
                    case 1: {
                        // 0x19ca
                        v16 = v11 - *v14;
                        // break -> 0x19f6
                        break;
                    }
                }
            }
            // 0x19f6
            *v14 = v16;
            // 0x1a46
            return (int32_t *)(int64_t)v14;
        }
        case 0: {
            int32_t v18 = _Z6lookupP5tablePKc(a2, (char *)*(int64_t *)((int64_t)a1 + 8)); // 0x1914
            *(int32_t *)v3 = v18;
            int64_t v19 = (int64_t)v3; // 0x191f
            *(int64_t *)(v19 + 8) = v8;
            // 0x1a46
            return (int32_t *)v19;
        }
        case 1: {
            // 0x1934
            *(int32_t *)v3 = *(int32_t *)((int64_t)a1 + 8);
            int64_t v20 = (int64_t)v3; // 0x1941
            *(int64_t *)(v20 + 8) = v8;
            // 0x1a46
            return (int32_t *)v20;
        }
    }
    // 0x1a46
    return (int32_t *)0;
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/main.hpp
// Address range: 0x1a48 - 0x1af4
// Line range:    210 - 226
// Demangled:     interpExpList(A_expList_*, table*)
int32_t * _Z13interpExpListP10A_expList_P5table(int64_t * a1, int64_t * a2) {
    // 0x1a48
    if (a1 == NULL) {
        // 0x1af2
        return (int32_t *)0;
    }
    // 0x1a6d
    _Z14checked_mallocm(16);
    int64_t v1 = 0; // 0x1a48
    int64_t v2; // 0x1a48
    switch ((int32_t)v2) {
        case 0: {
            int64_t v3 = (int64_t)a1; // 0x1a8c
            int32_t * v4 = _Z9interpExpP6A_exp_P5table((int64_t *)*(int64_t *)(v3 + 8), a2); // 0x1a9e
            int64_t v5 = *(int64_t *)((int64_t)v4 + 8); // 0x1aab
            int64_t v6 = *(int64_t *)(v3 + 16); // 0x1ab3
            v1 = (int64_t)_Z13interpExpListP10A_expList_P5table((int64_t *)v6, (int64_t *)v5);
            // break -> 0x1af2
            break;
        }
        case 1: {
            int64_t v7 = *(int64_t *)((int64_t)a1 + 8); // 0x1ad0
            v1 = (int64_t)_Z9interpExpP6A_exp_P5table((int64_t *)v7, a2);
            // break -> 0x1af2
            break;
        }
    }
    // 0x1af2
    return (int32_t *)v1;
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/main.hpp
// Address range: 0x1af4 - 0x1b18
// Line range:    231 - 233
// Demangled:     interp(A_stm_*)
void _Z6interpP6A_stm_(int64_t * a1) {
    // 0x1af4
    _Z9interpStmP6A_stm_P5table(a1, NULL);
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/main.hpp
// Address range: 0x1b18 - 0x1c7a
// Line range:    244 - 260
// Demangled:     prog_generator()
int32_t * _Z14prog_generatorv(void) {
    int32_t * v1 = _Z7A_IdExpPKc("c1"); // 0x1b33
    int32_t * v2 = _Z10A_PrintStmP10A_expList_((int64_t *)_Z13A_LastExpListP6A_exp_((int64_t *)v1)); // 0x1b43
    int32_t * v3 = _Z13A_LastExpListP6A_exp_((int64_t *)_Z7A_IdExpPKc("b")); // 0x1b5d
    int32_t * v4 = _Z13A_CompoundStmP6A_stm_S0_((int64_t *)_Z10A_PrintStmP10A_expList_((int64_t *)v3), (int64_t *)v2); // 0x1b70
    int32_t * v5 = _Z7A_IdExpPKc("a"); // 0x1b82
    int32_t * v6 = _Z7A_OpExpP6A_exp_7A_binopS0_((int64_t *)_Z8A_NumExpi(10), 2, (int64_t *)v5); // 0x1b9f
    int32_t * v7 = _Z8A_NumExpi(1); // 0x1bac
    int32_t * v8 = _Z7A_IdExpPKc("a"); // 0x1bbe
    int32_t * v9 = _Z13A_LastExpListP6A_exp_((int64_t *)_Z7A_OpExpP6A_exp_7A_binopS0_((int64_t *)v8, 1, (int64_t *)v7)); // 0x1bd6
    int32_t * v10 = _Z13A_PairExpListP6A_exp_P10A_expList_((int64_t *)_Z7A_IdExpPKc("a"), (int64_t *)v9); // 0x1bf3
    int32_t * v11 = _Z9A_EseqExpP6A_stm_P6A_exp_((int64_t *)_Z10A_PrintStmP10A_expList_((int64_t *)v10), (int64_t *)v6); // 0x1c06
    int32_t * v12 = _Z13A_CompoundStmP6A_stm_S0_((int64_t *)_Z11A_AssignStmPKcP6A_exp_("b", (int64_t *)v11), (int64_t *)v4); // 0x1c23
    int32_t * v13 = _Z8A_NumExpi(3); // 0x1c30
    int32_t * v14 = _Z8A_NumExpi(5); // 0x1c3d
    return _Z13A_CompoundStmP6A_stm_S0_((int64_t *)_Z11A_AssignStmPKcP6A_exp_("a", (int64_t *)_Z7A_OpExpP6A_exp_7A_binopS0_((int64_t *)v14, 0, (int64_t *)v13)), (int64_t *)v12);
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/main.hpp
// Address range: 0x1c7a - 0x1ee1
// Line range:    270 - 305
// Demangled:     prog_generator2()
int32_t * _Z15prog_generator2v(void) {
    int32_t * v1 = _Z13A_LastExpListP6A_exp_((int64_t *)_Z7A_IdExpPKc("c10")); // 0x1c9d
    int32_t * v2 = _Z13A_PairExpListP6A_exp_P10A_expList_((int64_t *)_Z7A_IdExpPKc("c9"), (int64_t *)v1); // 0x1cba
    int32_t * v3 = _Z13A_PairExpListP6A_exp_P10A_expList_((int64_t *)_Z7A_IdExpPKc("c8"), (int64_t *)v2); // 0x1cd7
    int32_t * v4 = _Z13A_PairExpListP6A_exp_P10A_expList_((int64_t *)_Z7A_IdExpPKc("c7"), (int64_t *)v3); // 0x1cf4
    int32_t * v5 = _Z13A_PairExpListP6A_exp_P10A_expList_((int64_t *)_Z7A_IdExpPKc("c6"), (int64_t *)v4); // 0x1d11
    int32_t * v6 = _Z13A_PairExpListP6A_exp_P10A_expList_((int64_t *)_Z7A_IdExpPKc("c5"), (int64_t *)v5); // 0x1d2e
    int32_t * v7 = _Z13A_PairExpListP6A_exp_P10A_expList_((int64_t *)_Z7A_IdExpPKc("c4"), (int64_t *)v6); // 0x1d4b
    int32_t * v8 = _Z13A_PairExpListP6A_exp_P10A_expList_((int64_t *)_Z7A_IdExpPKc("c3"), (int64_t *)v7); // 0x1d68
    int32_t * v9 = _Z13A_PairExpListP6A_exp_P10A_expList_((int64_t *)_Z7A_IdExpPKc("c2"), (int64_t *)v8); // 0x1d85
    int32_t * v10 = _Z7A_IdExpPKc("c1"); // 0x1d97
    int32_t * v11 = _Z10A_PrintStmP10A_expList_((int64_t *)_Z13A_PairExpListP6A_exp_P10A_expList_((int64_t *)v10, (int64_t *)v9)); // 0x1daa
    int32_t * v12 = _Z13A_LastExpListP6A_exp_((int64_t *)_Z7A_IdExpPKc("b")); // 0x1dc4
    int32_t * v13 = _Z13A_CompoundStmP6A_stm_S0_((int64_t *)_Z10A_PrintStmP10A_expList_((int64_t *)v12), (int64_t *)v11); // 0x1dd7
    int32_t * v14 = _Z7A_IdExpPKc("a"); // 0x1de9
    int32_t * v15 = _Z7A_OpExpP6A_exp_7A_binopS0_((int64_t *)_Z8A_NumExpi(10), 2, (int64_t *)v14); // 0x1e06
    int32_t * v16 = _Z8A_NumExpi(1); // 0x1e13
    int32_t * v17 = _Z7A_IdExpPKc("a"); // 0x1e25
    int32_t * v18 = _Z13A_LastExpListP6A_exp_((int64_t *)_Z7A_OpExpP6A_exp_7A_binopS0_((int64_t *)v17, 1, (int64_t *)v16)); // 0x1e3d
    int32_t * v19 = _Z13A_PairExpListP6A_exp_P10A_expList_((int64_t *)_Z7A_IdExpPKc("a"), (int64_t *)v18); // 0x1e5a
    int32_t * v20 = _Z9A_EseqExpP6A_stm_P6A_exp_((int64_t *)_Z10A_PrintStmP10A_expList_((int64_t *)v19), (int64_t *)v15); // 0x1e6d
    int32_t * v21 = _Z13A_CompoundStmP6A_stm_S0_((int64_t *)_Z11A_AssignStmPKcP6A_exp_("b", (int64_t *)v20), (int64_t *)v13); // 0x1e8a
    int32_t * v22 = _Z8A_NumExpi(3); // 0x1e97
    int32_t * v23 = _Z8A_NumExpi(5); // 0x1ea4
    return _Z13A_CompoundStmP6A_stm_S0_((int64_t *)_Z11A_AssignStmPKcP6A_exp_("a", (int64_t *)_Z7A_OpExpP6A_exp_7A_binopS0_((int64_t *)v23, 0, (int64_t *)v22)), (int64_t *)v21);
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/main.hpp
// Address range: 0x1ee1 - 0x1ff6
// Line range:    307 - 319
int main() {
    int32_t * v1 = _Z14prog_generatorv(); // 0x1eee
    int64_t v2 = _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc((int64_t *)&g2, "Program 1 print maxargs:\n"); // 0x1f0b
    _Z7maxargsP6A_stm_((int64_t *)v1);
    _ZNSolsEPFRSoS_E((int64_t * (*)(int64_t *))_ZNSolsEi((int32_t)v2));
    int32_t * v3 = _Z15prog_generator2v(); // 0x1f3b
    int64_t v4 = _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc((int64_t *)&g2, "Program 2 print maxargs:\n"); // 0x1f58
    _Z7maxargsP6A_stm_((int64_t *)v3);
    _ZNSolsEPFRSoS_E((int64_t * (*)(int64_t *))_ZNSolsEi((int32_t)v4));
    _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc((int64_t *)&g2, "Program 1:\n");
    _Z6interpP6A_stm_((int64_t *)v1);
    _ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc((int64_t *)&g2, "Program 2:\n");
    _Z6interpP6A_stm_((int64_t *)v3);
    _ZNSolsEPFRSoS_E((int64_t * (*)(int64_t *))&g2);
    return 0;
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/main.hpp
// Address range: 0x1ff6 - 0x2016
// Line range:    9 - 11
// Demangled:     int max<int>(int, int)
int32_t _Z3maxIiET_S0_S0_(int32_t a1, int32_t a2) {
    // 0x1ff6
    return a1 > a2 ? a1 : a2;
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/grammar_interpreter.cpp
// Address range: 0x2016 - 0x2060
// Line range:    4 - 10
// Demangled:     A_CompoundStm(A_stm_*, A_stm_*)
int32_t * _Z13A_CompoundStmP6A_stm_S0_(int64_t * a1, int64_t * a2) {
    char * v1 = _Z14checked_mallocm(24); // 0x202f
    int64_t v2 = (int64_t)v1; // 0x202f
    *(int32_t *)v1 = 0;
    *(int64_t *)(v2 + 8) = (int64_t)a1;
    *(int64_t *)(v2 + 16) = (int64_t)a2;
    return (int32_t *)v1;
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/grammar_interpreter.cpp
// Address range: 0x2060 - 0x20aa
// Line range:    12 - 18
// Demangled:     A_AssignStm(char const*, A_exp_*)
int32_t * _Z11A_AssignStmPKcP6A_exp_(char * a1, int64_t * a2) {
    char * v1 = _Z14checked_mallocm(24); // 0x2079
    int64_t v2 = (int64_t)v1; // 0x2079
    *(int32_t *)v1 = 1;
    *(int64_t *)(v2 + 8) = (int64_t)a1;
    *(int64_t *)(v2 + 16) = (int64_t)a2;
    return (int32_t *)v1;
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/grammar_interpreter.cpp
// Address range: 0x20aa - 0x20e4
// Line range:    20 - 26
// Demangled:     A_PrintStm(A_expList_*)
int32_t * _Z10A_PrintStmP10A_expList_(int64_t * a1) {
    char * v1 = _Z14checked_mallocm(24); // 0x20bf
    *(int32_t *)v1 = 2;
    *(int64_t *)((int64_t)v1 + 8) = (int64_t)a1;
    return (int32_t *)v1;
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/grammar_interpreter.cpp
// Address range: 0x20e4 - 0x211e
// Line range:    28 - 34
// Demangled:     A_IdExp(char const*)
int32_t * _Z7A_IdExpPKc(char * a1) {
    char * v1 = _Z14checked_mallocm(32); // 0x20f9
    *(int32_t *)v1 = 0;
    *(int64_t *)((int64_t)v1 + 8) = (int64_t)a1;
    return (int32_t *)v1;
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/grammar_interpreter.cpp
// Address range: 0x211e - 0x2155
// Line range:    36 - 42
// Demangled:     A_NumExp(int)
int32_t * _Z8A_NumExpi(int32_t a1) {
    char * v1 = _Z14checked_mallocm(32); // 0x2132
    *(int32_t *)v1 = 1;
    *(int32_t *)((int64_t)v1 + 8) = a1;
    return (int32_t *)v1;
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/grammar_interpreter.cpp
// Address range: 0x2155 - 0x21ac
// Line range:    44 - 50
// Demangled:     A_OpExp(A_exp_*, A_binop, A_exp_*)
int32_t * _Z7A_OpExpP6A_exp_7A_binopS0_(int64_t * a1, int64_t a2, int64_t * a3) {
    char * v1 = _Z14checked_mallocm(32); // 0x2171
    int64_t v2 = (int64_t)v1; // 0x2171
    *(int32_t *)v1 = 2;
    *(int64_t *)(v2 + 8) = (int64_t)a1;
    *(int32_t *)(v2 + 16) = (int32_t)a2;
    *(int64_t *)(v2 + 24) = (int64_t)a3;
    return (int32_t *)v1;
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/grammar_interpreter.cpp
// Address range: 0x21ac - 0x21f6
// Line range:    52 - 58
// Demangled:     A_EseqExp(A_stm_*, A_exp_*)
int32_t * _Z9A_EseqExpP6A_stm_P6A_exp_(int64_t * a1, int64_t * a2) {
    char * v1 = _Z14checked_mallocm(32); // 0x21c5
    int64_t v2 = (int64_t)v1; // 0x21c5
    *(int32_t *)v1 = 3;
    *(int64_t *)(v2 + 8) = (int64_t)a1;
    *(int64_t *)(v2 + 16) = (int64_t)a2;
    return (int32_t *)v1;
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/grammar_interpreter.cpp
// Address range: 0x21f6 - 0x2240
// Line range:    60 - 66
// Demangled:     A_PairExpList(A_exp_*, A_expList_*)
int32_t * _Z13A_PairExpListP6A_exp_P10A_expList_(int64_t * a1, int64_t * a2) {
    char * v1 = _Z14checked_mallocm(24); // 0x220f
    int64_t v2 = (int64_t)v1; // 0x220f
    *(int32_t *)v1 = 0;
    *(int64_t *)(v2 + 8) = (int64_t)a1;
    *(int64_t *)(v2 + 16) = (int64_t)a2;
    return (int32_t *)v1;
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/grammar_interpreter.cpp
// Address range: 0x2240 - 0x227a
// Line range:    68 - 74
// Demangled:     A_LastExpList(A_exp_*)
int32_t * _Z13A_LastExpListP6A_exp_(int64_t * a1) {
    char * v1 = _Z14checked_mallocm(24); // 0x2255
    *(int32_t *)v1 = 1;
    *(int64_t *)((int64_t)v1 + 8) = (int64_t)a1;
    return (int32_t *)v1;
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/utils.cpp
// Address range: 0x227a - 0x22cf
// Line range:    16 - 21
// Demangled:     checked_malloc(unsigned long)
char * _Z14checked_mallocm(int64_t size) {
    int64_t * mem = malloc((int32_t)size); // 0x2291
    if (mem == NULL) {
        // 0x22a1
        __assert_fail("p", "src/utils.cpp", 19, "void* checked_malloc(std::size_t)");
    }
    // 0x22c9
    return (char *)mem;
}

// From module:   /home/flower/simple_tiger_compiler/project_homedir/utils.cpp
// Address range: 0x22cf - 0x2314
// Line range:    23 - 28
// Demangled:     String(char const*)
char * _Z6StringPKc(char * str) {
    char * str2 = _Z14checked_mallocm((int64_t)strlen(str) + 1); // 0x22f2
    strcpy(str2, str);
    return str2;
}

// Address range: 0x2314 - 0x2321
int64_t _fini(void) {
    // 0x2314
    int64_t result; // 0x2314
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (13.2.0)
// Detected functions: 43

