.TH "src/SLP_interpreter Directory Reference" 3 "A simple tiger compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/SLP_interpreter Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgrammar_interpreter\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgrammar_interpreter\&.hpp\fP"
.br
.RI "realize of grammar "
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmain\&.hpp\fP"
.br
.in -1c
