.TH "A_expList_" 3 "A simple tiger compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
A_expList_
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <grammar_interpreter\&.hpp>\fP
.SS "Public Types"
.SS "Data Fields"
.SH "Detailed Description"
.PP 

.PP
.nf
ExpList \-> Exp, ExpList
ExpList \-> Exp

.fi
.PP
 
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIA_pairExpList \fP\fP
.TP
\fB\fIA_lastExpList \fP\fP
.SH "Field Documentation"
.PP 
.SS "\fBA_exp\fP head"

.SS "enum  { \&.\&.\&. }  kind"

.SS "\fBA_exp\fP last"

.SS "struct  { \&.\&.\&. }  pair"

.SS "\fBA_expList\fP tail"

.SS "union  { \&.\&.\&. }  u"


.SH "Author"
.PP 
Generated automatically by Doxygen for A simple tiger compiler from the source code\&.
