.TH "int_and_table" 3 "A simple tiger compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
int_and_table
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <main\&.hpp>\fP
.SS "Data Fields"
.SH "Field Documentation"
.PP 
.SS "int i"

.SS "\fBTable_\fP tail"


.SH "Author"
.PP 
Generated automatically by Doxygen for A simple tiger compiler from the source code\&.
