.TH "SLP_interpreter" 3 "A simple tiger compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SLP_interpreter \- SLP_interpreter
.PP
 \- an interpreter to Straight-Line Program(SLP) language  

.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgrammar_interpreter\&.hpp\fP"
.br
.RI "realize of grammar "
.in -1c
.SH "Detailed Description"
.PP 
an interpreter to Straight-Line Program(SLP) language 


.SH "Function Documentation"
.PP 
.SS "template<typename T  = int> T max (T a, T b)"

.SH "<tt>__main__</tt> file"
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for A simple tiger compiler from the source code\&.
