.TH "table" 3 "A simple tiger compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
table
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <main\&.hpp>\fP
.SS "Data Fields"
.SH "Field Documentation"
.PP 
.SS "\fBstring\fP id"

.SS "\fBTable_\fP tail"

.SS "int value"


.SH "Author"
.PP 
Generated automatically by Doxygen for A simple tiger compiler from the source code\&.
