.TH "utils" 3 "A simple tiger compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils \- Utils
.PP
 \- realize of \fButils\&.hpp\fP  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
realize of \fButils\&.hpp\fP 

USE ASSERT!!! 
.SH "Author"
.PP 
Generated automatically by Doxygen for A simple tiger compiler from the source code\&.
