.TH "src/utils.cpp" 3 "A simple tiger compiler" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils.cpp
.SH SYNOPSIS
.br
.PP
.SH "Function Documentation"
.PP 
.SS "void* checked_malloc (std::size_t size)"

.PP
Don't use \fCnew\fP/\fCdelete\fP(C++), \fCmalloc\fP/\fCcalloc\fP/\fCfree\fP(C) In C++, memory allocator in <cstdlib> 
.PP
\fBWarning\fP
.RS 4
malloc will return NULL (C) or nullptr (C++>=11) 
.RE
.PP

.SS "\fBstring\fP String (\fBstring\fP origin)"

.PP
string constructor 
.SH "Author"
.PP 
Generated automatically by Doxygen for A simple tiger compiler from the source code\&.
